### ISSUE TITLE
Gripmock UI Loading issue

### ISSUE THREAD

**Issue by ATamEstChange** [bavix/gripmock#421]
![image](https://github.com/user-attachments/assets/dfad3b3b-f517-47b6-a303-44763f2c76ba)

### Error:
```
react-admin-YFQLaSRa.js:8 Uncaught ReferenceError: Cannot access 'a1' before initialization
    at Z (react-admin-YFQLaSRa.js:8:26455)
    at react-admin-YFQLaSRa.js:8:26569
    at Array.forEach (<anonymous>)
    at ee (react-admin-YFQLaSRa.js:8:26552)
    at mui-DXdGyifB.js:1:906
```

Browser: Google Chrome Version 130.0.6723.91 (Official Build) (64-bit)
OS: Ubuntu

**Comment by rez1dent3** [comment]
Hello. Yes, I know about it. I had the fix on my local machine, pushed it to GitHub and built fresh versions of gripmock ui.

Gripmock 3.x itself is still in beta, and 2.x is without ui.

The UI is raw, very raw and does not support editing normally. I will finish it later, now I am concentrating on the new version of search, which is integrated into version 3.x.

---

I started the UI fix build. It will be built in 10-15 minutes, I think. You can try it on latest or master versions.

You can track the build status here:
https://github.com/bavix/gripmock/actions/runs/11667528012/job/32485036483

Thank you for your feedback.

**Comment by rez1dent3** [comment]
@ATamEstChange Is your original problem solved in the latest and/or master tags?

**Comment by rez1dent3** [comment]
I will close the issue. If you have any questions, please create a new one.

**Comment by ATamEstChange** [comment]
Thanks. It works!
